### ISSUE TITLE
afterprice rendered after tier price display but does not take discount into account

### ISSUE THREAD

**Issue by fwolfst** [Magenerds/BasePrice#15]
In a magento 2.1.9 installation base prices are shown in the relevant places.
If the product has a tier price ("buy 2 for xxx and save yy%") configured, the afterprice is rendered afterwards, but shows the same values as for the "single" price.

**Comment by sydekumf** [comment]
Hi, thanks for the report :-)

The tier price block is pretty complex and calculated in one template: `module-catalog/view/base/templates/product/price/tier_prices.phtml`. There you can see the `ul` list and in order to inject the base price there you have to override the complete template. As we consider that change as not justifiable (as custom themes may override on their own way), we skip this.

But it is relatively easy to change it in your individual Magento instance. Just overwrite the template and call the helper `Magenerds\BasePrice\Helper\Data::getBasePriceText()`. Take `getBasePriceText()` as a boilerplate to adjust to calculate the tier prices.

Thanks :-)

**Comment by fwolfst** [comment]
Thanks for the help! But having said that, I have absolutely no idea how to get an instance of that helper in the tierprice-template, but I'll find my way.

Before opening an issue about that, I have noticed that the headers of source files contradict the statment in `composer.json` (where OSL is mentioned). Should that be adressed?

**Comment by fwolfst** [comment]
Okay, i do come closer. However, how do I prevent the ("unscaled") base price been rendered after the tier price? As is, the base price is rendered twice, if a tier price is present.
