### ISSUE TITLE
ReflectionException, SerializerInterface does not exist

### ISSUE THREAD

**Issue by hhusen** [Magenerds/BasePrice#27]
BasePrice 1.2.0 and 1.2.1 is not installable. Error during install:

> php ./bin/magento setup:di:compile
> 
> Area configuration aggregation... 5/7 [====================>-------]  71% 34 secs 184.0 MiBMiB
> 
>   [ReflectionException]
>   Class Magento\Framework\Serialize\SerializerInterface does not exist

Problem exists since trying update from 1.1.1 to 1.2.0 (should fix rendering of duplicate information for empty tier prices)

1.1.1 works, but shows the duplicate rendering error.

Magento version: 2.1.11

**Comment by sydekumf** [comment]
Hey, the 1.2.0 and 1.2.1 are only compatible to M 2.2, that's why you get the error. So you either upgrade to M 2.2 or you use the duplicate rendering bugfix commits:
https://github.com/Magenerds/BasePrice/commit/0237ee98c5bf5ddf74df869196fde166fc632dc2
https://github.com/Magenerds/BasePrice/commit/e7e5a602c5c244eb98cda47973feb0b1d354f29d

**Comment by Eugenett** [comment]
The problem is resolved
